// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqUx5Fd6BiOzcUkPqTEq2oK3M4PNeEN18',
    appId: '1:239222141183:web:c6ebce4487926ed902dcca',
    messagingSenderId: '239222141183',
    projectId: 'socials-7c1b9',
    authDomain: 'socials-7c1b9.firebaseapp.com',
    storageBucket: 'socials-7c1b9.appspot.com',
    measurementId: 'G-Z3H083C1DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnXiFL7M23vM88z0218urs0TXUpgkKL4g',
    appId: '1:239222141183:android:61b6f469e86bcdb002dcca',
    messagingSenderId: '239222141183',
    projectId: 'socials-7c1b9',
    storageBucket: 'socials-7c1b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3DCSlL-x-wtTOqhBl7GlyLuTlIe05ODc',
    appId: '1:239222141183:ios:57f0e19368e1a3ad02dcca',
    messagingSenderId: '239222141183',
    projectId: 'socials-7c1b9',
    storageBucket: 'socials-7c1b9.appspot.com',
    iosBundleId: 'com.example.socials',
  );
}
